name: Go Test Build and Deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.0
      
    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build -v -o bm ./cmd/api

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: bm-artifact
          path: ./bm
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: bm-artifact

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           source: ./bm
           target: "/home/${{ secrets.USERNAME }}/bm"

      - name: Start Book Moview Backend API service and Reload Nginx
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           script: |
               cd /home/${{ secrets.USERNAME }}/bm
               chmod +x bm
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl stop bm.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl start bm.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl reload nginx
